### PR TITLE
🇲🇹 Add Proxy Node deployment for Malta in integration

### PR DESCRIPTION
**Pull request by CharlesIC**

### CODE REVIEW

**Review by JohnWattsGDS — APPROVED** [review]

**Comment by Wynndow** [comment]
Where did the trust-anchor come from? I'm struggling to see it on the CEF page and can't see it in the zendesk ticket.

**Comment by CharlesIC** [comment]
@Wynndow From the metadata itself - they publish a different cert on CEF - I'm assuming they haven't updated CEF. But in any case the published cert is a leaf metadata singing cert so instead I just took the leaf cert from the current published metadata.

**Comment by Wynndow** [comment]
I don't think we want to trust something that we just grabbed from the metadata. We should be getting it from them directly, or from their CEF page.

**Comment by CharlesIC** [comment]
You're right - but for integration this is okay

**Review by Wynndow — APPROVED** [review]
Yep, fair enough

**Pull request merged**
