### PR TITLE
EID-1919 Second stab at a sealed secret

### PR DESCRIPTION
**Pull request by JohnWattsGDS**
Encrypt an actual certificate instead of a github page

### CODE REVIEW

**Comment by blairboy362** [comment]
Someone with admin powers will also need to go in and delete the sealed secret and secret with the old name.

**Comment by JohnWattsGDS** [comment]
I'll check with Phil that I haven't messed up the name too.

**Comment by JohnWattsGDS** [comment]
I changed the name so does someone with admin powers still also need to go in and delete the sealed secret and "secret with the old name" (now that there isn't an old name).  Or rather - does anything need deleting or will it be overwritten?

**Comment by blairboy362** [comment]
If the name is the same then it will just overwrite. No one will need to go in and tidy up afterwards.

**Pull request merged**
